### ISSUE TITLE
Usage description

### ISSUE THREAD

**Issue by abourget** [ossrs/httpx-static#51]
This repository would attract _much_ more interest if there was a simple "Usage" section. I found this README.md file here https://github.com/winterserver/simple-rtmp-server that shows how to use the server, and all of a sudden I thought maybe `go-oryx` was useful too!

Please add a tiny `Usage` section in the README.md.. it's rough to dive into it.. I just tried to install the software now that I think it can be useful .. otherwise, nothing says anywhere what it does, or doesn't do.

thanks a lot :)

**Comment by abourget** [comment]
Never mind.. I though the "Usage" section was an installation section because of the `go get` calls.

Should have looked better!

**Comment by winlinvip** [comment]
winterserver/simple-rtmp-server is deprecated and removed.
