### ISSUE TITLE
ffmpeg推流成功，但vlc播放失败。

### ISSUE THREAD

**Issue by wotheai** [ossrs/httpx-static#54]
我conf/oryx.conf的配置如下：
{
  "listen": 1935,
  "log": {
    "tank": "file",
    "level":
    "file": "oryx.log"
  },
  "vhosts": [
    {
      "name": "**defaultVhost**"
    }
  ]
}

我ffmpeg推流命令如下：
ffmpeg -re -i Pulp.Fiction.1994.BluRay.1080p.DTSMA.x264-CHD.mkv -vcodec libx264 -preset veryfast  -s 480x320 -maxrate 600k -bufsize 6000k -pix_fmt yuv420p -g 50 -acodec libmp3lame -b:a 128k -ac 2 -ar 44100 -f flv rtmp://127.0.0.1:1935/myapp/test

逻辑上，我的播放地址就应该是：rtmp://127.0.0.1:1935/myapp/test，当然，我把127.0.0.1这个改成了可以访问的192.168.0.80。
但我的VLC播放失败。oryx的日志如下：
[oryx][trace] 2016/03/14 13:15:02 [7705][102] rtmp accept 192.168.0.59:14514
[oryx][trace] 2016/03/14 13:15:02 [7705][102] complex handshake ok.
[oryx][trace] 2016/03/14 13:15:02 [7705][102] connect at rtmp://192.168.0.80:1935/myapp AMF0
[oryx][trace] 2016/03/14 13:15:02 [7705][102] output chunk size to 60000
[oryx][trace] 2016/03/14 13:15:02 [7705][102] client identified, type=unknown, stream_name=, duration=0.00
[oryx][trace] 2016/03/14 13:15:02 [7705][102] redirect vhost 192.168.0.80 to **defaultVhost**
[oryx][warn] 2016/03/14 13:15:02 [7705][102] close invalid unknown client
[oryx][warn] 2016/03/14 13:15:02 [7705][102] read basic header failed. err is read tcp 192.168.0.80:1935->192.168.0.59:14514: use of closed network connection
[oryx][warn] 2016/03/14 13:15:02 [7705][102] rtmp receiver terminated with read tcp 192.168.0.80:1935->192.168.0.59:14514: use of closed network connection
[oryx][trace] 2016/03/14 13:15:02 [7705][102] closed
[oryx][trace] 2016/03/14 13:15:19 [7705][103] rtmp accept 192.168.0.59:14518
[oryx][trace] 2016/03/14 13:15:19 [7705][103] complex handshake ok.
[oryx][trace] 2016/03/14 13:15:19 [7705][103] connect at rtmp://192.168.0.80:1935/myapp AMF0
[oryx][trace] 2016/03/14 13:15:19 [7705][103] output chunk size to 60000
[oryx][trace] 2016/03/14 13:15:19 [7705][103] client identified, type=unknown, stream_name=, duration=0.00
[oryx][trace] 2016/03/14 13:15:19 [7705][103] redirect vhost 192.168.0.80 to **defaultVhost**
[oryx][warn] 2016/03/14 13:15:19 [7705][103] close invalid unknown client
[oryx][warn] 2016/03/14 13:15:19 [7705][103] read basic header failed. err is read tcp 192.168.0.80:1935->192.168.0.59:14518: use of closed network connection
[oryx][warn] 2016/03/14 13:15:19 [7705][103] rtmp receiver terminated with read tcp 192.168.0.80:1935->192.168.0.59:14518: use of closed network connection
[oryx][trace] 2016/03/14 13:15:19 [7705][103] closed

请问何故？

**Comment by winlinvip** [comment]
```
close invalid unknown client
```

貌似是oryx主动关闭了连接。先别用VLC播放呗？

**Comment by daozhao** [comment]
ffplay 也有同样的情况。

**Comment by winlinvip** [comment]
用flash播放器吧，oryx还没有做兼容：
http://www.ossrs.net/players/srs_player.html
