### ISSUE TITLE
Modify imports ordering with goimport

### ISSUE THREAD

**Issue by mbeacom** [ossrs/httpx-static#59]
With `goimport`, all of the imports will be restructured to adhere to golang import package precedence and ordering by https://godoc.org/golang.org/x/tools/cmd/goimports to make it a little cleaner

**Comment by winlinvip** [comment]
I will study it.

**Comment by Akagi201** [comment]
@winlinvip @mbeacom I found the easy solution. Just run `goimports -w .` on the root of the repo. It will format all the codes and write the changes to the file.

**Comment by mbeacom** [comment]
@winlinvip `goimports -w .` against the project root will replicate the changes proposed in #60 
Thanks @Akagi201

**Comment by winlinvip** [comment]
Got it
