### ISSUE TITLE
go-oryx 并发9000个卡死

### ISSUE THREAD

**Issue by T-bag-A** [ossrs/httpx-static#65]
1.开启3个sb_rtmp_load进程 各播放3000个视频，视频会卡的不动了。内存占用达到64%（8G内存）
2.把3个压测进程关闭，内存没有释放，继续播放也是卡死。

**Comment by winlinvip** [comment]
可能触发bug了，oryx还没有发布，不建议用。

**Comment by winlinvip** [comment]
目前Oryx使用代理结构，可以再试试了，由后端SRS处理连接。
