### ISSUE TITLE
能否列一下目前支持的feature 和一个简单的tutorial

### ISSUE THREAD

**Issue by fastfading** [ossrs/httpx-static#74]
一直看好go 语言，简洁高效。比c++版本代码肯定少。
但是相对c++ 版本，这代码也太少了。
不确定现在有哪些feature 是支持的？

**Comment by winlinvip** [comment]
现在做的是基础库[go-oryx-lib](https://github.com/ossrs/go-oryx-lib)，还没有支持应用服务器（SRS是个应用服务器），当然有可能不会支持应用服务器。
目前的应用服务器，主要是代理，比如apilb、httplb、rtmplb、http转https。

**Comment by fastfading** [comment]
有一个简单的问题 想请教一下，  当rtmp 推送过来的时候，  rtmp 转 hls ts的过程中存在 video codec
的转码么？即视频是否重新编解码？
有些 ffmpeg 转换只是容器封装格式的转换，  其h.264数据帧并没有变化。
在srs 中这个过程是怎样的， 假设不改变原视频分辨率等数据参数。

2017-07-05 12:17 GMT+08:00 winlin <notifications@github.com>:

**Comment by winlinvip** [comment]
这个问题超过了这个issue的范围，建议加微信群问: https://github.com/ossrs/srs/wiki/v1_CN_Contact#wechat
